### ISSUE TITLE
Plugin doesn't scroll horisontally

### ISSUE THREAD

**Issue by da411d** [AMPivovarov/FastMouseScroll#4]
If i drag up or down, it scrolls normally. If i drag left or right - it doesn't

**Comment by da411d** [comment]
Oh sory, accidently found randomly read the update notes=)

I think you need to write minimalistic documentation, what do you think?

**Comment by AMPivovarov** [comment]
It is mentioned in "General Usage Instructions" field ("Installation and configuration instructions.").
But it looks like noone scrolls plugin page that far, and (for some reason) that field is not visible "Settings | Plugins" in IDE.
Will try to move it into plugin description.
