### ISSUE TITLE
Scrolling in Database table view

### ISSUE THREAD

**Issue by jhard** [AMPivovarov/FastMouseScroll#5]
I love FastMouseScroll, you really only appreciate it fully when it doesn't work.
Using the Database table/data viewer in PHPStorm, FMS seems to work neither vertically nor horizontally (Fast Mouse Scrolling is set to "both").
Is there any other setting that is required?

PhpStorm 2020.2.3
Build #PS-202.7660.42, built on October 16, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-54-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3959M
Cores: 24
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: A move tab left and right using the keyboard plugin - by momomo.com, com.jan.evendarker, com.jetbrains.fast.mouse.scroll, mobi.hsz.idea.gitignore, rocks.blackcat.vcl, com.perl5, com.intellij.plugins.html.instantEditing, lv.midiana.misc.phpstorm-plugins.deep-keys, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv
Current Desktop: KDE

**Comment by AMPivovarov** [comment]
It should work there.

It is possible that shortcut is consumed by something else (ex: "Editor Actions | Paste from X clipboard" or "Main Menu | Navigate | Go to Declaration or Usages" actions). 

Could you try to remove conflicting shortcuts from "File | Settings | Keymap" and check if it helps (see "Find actions by shortcut" on toolbar)?
Could you check if scrolling works when different components are 'focused' (ex: table itself, input field at the top, some toolwindow)?

**Comment by jhard** [comment]
Thank you. I've just now tried to replicate it again and it works as expected, so I must've hit a bug elsewhere before.

**Comment by jhard** [comment]
I was able to replicate it, I believe, but I'm not sure it's FMS's responsibility.

It happens when the filter criteria field of the table view is focused. Hovering over the data view and middle-clicking has no effect in that case.
This is different from tool windows, e.g. if the terminal is open and focused, I can still middle-click & scroll around in the data view, the filter field seems to be an exception.
