### ISSUE TITLE
[Request] Only trigger scrolling when holding middle mouse so that middle click is still usable

### ISSUE THREAD

**Issue by MostHated** [AMPivovarov/FastMouseScroll#6]
Hey there,
    I would like to request that the scrolling only be triggered when holding middle mouse so that middle click is still usable, as I use my middle click as "Go to Declaration/Usages", so it is used probably more than any other shortcut, but I also *always* find myself trying to click and drag to scroll.

Thanks,
-MH

**Comment by AMPivovarov** [comment]
See reply in #3 (which looks like the same request).
If you can confirm that this approach works for you, I'll merge it as an option.
